### ISSUE TITLE
library interface

### ISSUE THREAD

**Issue by illiliti** [skeeto/u-config#2]
One of the pkgconf's killer features is a C library interface(libpkgconf) that, for example, muon (meson written in C) uses to provide a fully static binary that works everywhere.

Will u-config have such interface or it will remain executable only?

**Comment by skeeto** [comment]
My goal isn't to replace pkgconf, and certainly not libpkgconf, but to 
establish a pkg-config better suited to certain uses cases, particularly 
w64devkit. Anyone relying on libpkgconf should definitely keep using 
pkgconf.

The libpkgconf API is fundamentally incompatible with u-config. I didn't 
look at it until now, and it's lower-level than I expected. It includes 
object lifetime management, which in turn assumes something like a general 
purpose allocator under the hood.

If the libpkgconf API isn't important and an application just needs a high 
level interface to extract a partial shell command as a string, it could 
act as the platform layer and drive u-config through the command line 
interface — i.e. build an argv of what it wants — not unlike popen(), 
except without actually starting a subprocess. The caller would collect  
output via "os_write" probably into a buffer. The "os_fail" part is a 
little tricker since it won't return control directly, but that could be 
patched over with a longjmp. (This is essential how I plan to eventually 
build an afl fuzz test platform layer and a test suite platform layer.)

Beyond that I have no plans for a u-config library.

**Comment by illiliti** [comment]
OK, thanks
