### ISSUE TITLE
Undefined memcpy and memset linker error

### ISSUE THREAD

**Issue by N-R-K** [skeeto/u-config#3]
From the recent commit 4ef6c8207706951c25db1be40d6f7440922418f8:

> The memset and memcpy definitions are now written in C, using volatile
> to work around GCC miscompilation.

Unfortunately, this does not work when using -march=native (in my case, `native` resolves to `znver2`) and optimization level 1 or above. I get many undefined memset and memcpy linker error. I've tried adding `-ffreestanding` but that doesn't help either.

Slightly cleaned up output:

	[u-config master]~> make pkg-config-linux-amd64 OPT="-O3 -march=znver2"
	gcc -O3 -march=znver2 -fno-builtin -fno-pie -fwhole-program -fno-asynchronous-unwind-tables -o pkg-config-linux-amd64 linux_amd64_main.c -s -no-pie -nostdlib -Wl,--gc-sections \
	  -DPKG_CONFIG_LIBDIR="\"$(pkg-config   --variable pc_path pkg-config)\""
	ld: /tmp/ccsFW64H.o: in function `findpackage':
	linux_amd64_main.c:(.text+0x9273): undefined reference to `memset'
	ld: linux_amd64_main.c:(.text+0x9366): undefined reference to `memcpy'
	ld: linux_amd64_main.c:(.text+0x9590): undefined reference to `memcpy'
	ld: linux_amd64_main.c:(.text+0x9a6f): undefined reference to `memset'
	ld: linux_amd64_main.c:(.text+0x9aa1): undefined reference to `memcpy'
	ld: linux_amd64_main.c:(.text+0xa6e7): undefined reference to `memset'
	ld: linux_amd64_main.c:(.text+0xa719): undefined reference to `memcpy'
	collect2: error: ld returned 1 exit status
	make: *** [Makefile:30: pkg-config-linux-amd64] Error 1

Note that the above make command works fine on the previous commit (801d02e).

Also an interesting GCC flag to investigate is `-mstringop-strategy`. Running `make pkg-config-linux-amd64 OPT="-O3 -march=znver2 -mstringop-strategy=loop"` solves the issue above.

However, even this isn't always reliable either. I don't have the test cases atm, but IIRC there were some cases where it'd still generate `memset` calls for zero-initializing large arrays/structs.

One other thing I noticed was that if I copy paste that `memset` and `memcpy` into godbolt, they don't seem to be getting "optimized" into infinite recursive calls. So as a completely blind guess, I figured what's going on is this:

* `-fwhole-program` turning your mem{cpy,set} into static functions.
* GCC sees they're not called anywhere (explicitly) and removes them.
* Then gcc inserts it's own memset/memcpy calls and leaves you with undefined references.

To confirm my theory, I added `__attribute((externally_visible))` to both the memcpy and memset definition and ran `make pkg-config-linux-amd64 OPT="-O3 -march=znver2"` again and now it works.

> I've found using it solves a number of other issues

Curious what they are. Care to elaborate?

**Comment by N-R-K** [comment]
Also, slightly relavant, from [glibc manual](https://www.gnu.org/software/libc/manual/html_node/Erasing-Sensitive-Data.html):

> Attempting to erase a normal variable “by hand” through a volatile-qualified pointer doesn’t work at all—because the variable itself is not volatile, some compilers will ignore the qualification on the pointer and remove the erasure anyway.

I don't think I'd be surprised if this was true, but I'm a bit skeptical of this. I have not seen this occur in practice and [this paper](https://www.usenix.org/conference/usenixsecurity17/technical-sessions/presentation/yang) from 2017 also declares "pointer to volatile char" as "effective in practice".

**Comment by skeeto** [comment]
Thanks for catching this, and for the careful detail! I can reproduce with 
"-march=znver2" as well, but *only* that arch. Strange, I would not have 
expected the arch to have this impact. Your -fwhole-program diagnosis is 
indeed correct. As far as I'm concerned, this a GCC bug. However, rather 
than work around it, I'm just going to drop -fwhole-program, treating it 
as a failed experiment. So far it's been nothing but disappointment and 
friction. Clang doesn't implement it, and it complains about both the 
compiler option and associated attribute.

I only just realized that you reported this on GitHub, not my mailing 
list, so my apologies for not referencing this issue from the commit 
(60b2264)! When I see your name I assume you're not using GitHub! (A 
decision I can totally understand.)

I'm curious why you're so interested in -O3, and especially -march. Isn't 
plain -Os enough for you?! :-) If I run it 1000 times selecting several 
packages, I can just barely measure a ~1% difference. Even -O0 is only 
~10% slower, and yet that's still twice as fast as my system pkg-config.
In this case, I use -Os less for performance and more for minimizing the 
installation size. With a bit of manual intervention in a hex editor, I 
was able to get the i686 static binary under 20kB. (That discussion is 
probably worth a whole article.)

> -mstringop-strategy=loop

Now that's very interesting. When I use this in old experiments, GCC stops 
producing *any* string function references. You know, exactly behavior I 
want and expect from -fno-builtin alone! Unfortunately Clang does not 
(yet?) implement it, and it's generally worse than GCC about inserting 
string function calls. I'll have to keep the mem{cpy,set} for Clang, but 
perhaps it's worth putting this in the Makefile where it's reasonable to 
assume it's GCC…

I was also experimenting with compiling with tcc (mob), using my own tcc 
fork which "supports" __builtin_unreachable(). It also needs a memmove, 
which, unfortunately, is a bit trickier to get right! I just pushed my tcc 
WIP branch in case you're interested. I'm more forgiving of tcc inserting 
string function calls. It's designed not to be fancy. mob tcc can do GNU 
inline assembly, but not quite well enough, hence the external assembly.

>> I've found using it solves a number of other issues
> Curious what they are. Care to elaborate?

I really need to write these down when I come across them! You can observe 
one yourself with the recent changes:

$ i686-linux-gnu-gcc -nostdlib -Wextra linux_i686_main.c

You'll get two -Wbuiltin-declaration-mismatch warnings about mem{cpy,set} 
having the wrong prototypes. (These string function calls are the root of 
so many unnecessary problems!) For i686-linux-gnu GCC, size_t is "unsigned 
int" but on 64-bit hosts it's "unsigned long". A rather unfortunate choice 
of definition, as "long" is a reliable pointer sized integer on Linux, and 
just right for sizes. (It annoys me this is not the case on Windows.) This 
decision was probably made very early, before knowledge of the form 64-bit 
computing would take, and of course could not be changed without breaking 
ABI.

Using the "wrong" type for size_t has consequences for strict aliasing and 
integer promotion, but no effect in this case. -fno-builtin dismisses the 
warnings. I could instead include stddef.h for the "right" size_t. That 
header is part of the compiler, not libc, so it would be harmless.

There have been other cases where a similarly noisy result basically 
means, "You forgot -fno-builtin, dummy." I'll add them here when I 
remember/see them again. Per my "scratch" activity, these days my Windows 
development is all CRT-free, and so I've been spending a lot more time in 
this niche space, bumping into odd compiler issues, MSVC included.

> I have not seen this occur in practice

I'm not worried about that case since that's for a different, unrelated 
purpose. In that context it's about erasing memory so thoroughly that it's 
inaccessible even through undefined behavior. In u-config, I don't care 
about that, and eliding the stores is fine. Instead, volatile establishes 
stricter semantics than mem{cpy,set}, so that GCC cannot replace the loop 
with a string function call.

How is it stricter? volatile forces an ordering on loop iterations — bytes 
must be written in order — which mem{cpy,set} not only does not guarantee, 
but glibc famously runs memcpy in reverse, which caused no small amount of 
controversy back in 2010 (glibc 2.14). Technically the semantics are still 
the same for "len < 2" but I don't expect compilers to make that a special 
case string function call. That would be a terrible "optimization."

**Comment by N-R-K** [comment]
> I can reproduce with "-march=znver2" as well, but *only* that arch.
> When I see your name I assume you're not using GitHub!
> I'm curious why you're so interested in -O3, and especially -march.

For some context: I've recently been toying around with GCC's extended asm
along with trying out a "libc-free" platform layer:
https://codeberg.org/NRK/slashtmp/src/branch/master/misc/fate/fate-linux-amd64.c

During it, I noticed that `-march=native` was sometimes having effect on string
optimizations. And in general, `-O3` along with some other aggressive flags like
`-fipa-pta -fgraphite-identity -floop-nest-optimize` tends to reveal bugs...
sometimes in the code and sometimes in the compiler :)

So when I saw that u-config commit in my RSS feed, I figured I should try it
out to see if it reveals anything - and indeed it did. Initially, I had written
this out as a short comment under that commit (which was linked on my RSS feed)
on Github. But as I investigated and started more details there, I realized
that it's probably worth it's own issue.

TBH, I was always assuming this was due to AVX + SSE + whatnot being available
to the compiler that was triggering some specific optimization pass. I never
would've guessed that `znver2` in specific was the culprit. In fact, I only
added the `znver2` detail in my issue as an FYI, not because I thought it would
be necessary to reproduce!

> plain -Os enough for you?!

As explained above, I was mainly doing it to see if anything comes up, not for
performance. But on this topic, musl has actually been trying to move away from
-Os https://www.openwall.com/lists/musl/2023/05/22/2

| mainly because it imposes a few really ugly pessimizations without their own
| switches, like forcing use of div instructions for div-by-constant [...]
| because the mul takes a couple more bytes of .text

(Not a big deal for a pkg-config clone as your benchmarks shown, but might be
 worth keeping in mind for more performance sensitive programs).
 
And on the size topic, have you considered using `upx`? https://upx.github.io/
`-O2` + `upx --best --no-lzma` seems to produce results similar to `-Os` size.

> You'll get two -Wbuiltin-declaration-mismatch warnings about mem{cpy,set}
> having the wrong prototypes.

I actually came across this warning too, but for different reason: I tried to
use `ptrdiff_t` as the size parameter.

> In that context it's about erasing memory so thoroughly that it's
> inaccessible even through undefined behavior. In u-config, I don't care
> about that, and eliding the stores is fine.

That wasn't my worry either, since u-config (obviously) doesn't hold sensitive
information in memory anyways. But rather, my concern was the "removing
volatile from pointer" part.

What I was thinking is that the compiler might:
1) inline the mem* calls
2) remove the mem* definitions
3) remove the volatile from the pointer since the object being pointed to wasn't volatile
4) do some "optimizations" and end up emitting a mem* call at the end

But since you're not definiting those mem* functions as `static` (and now that
`-fwhole-program` is out), the removing the definitions part probably cannot
occur anymore. So this would be harmless, even if it happens.

> Instead, volatile establishes stricter semantics than mem{cpy,set}, so that
> GCC cannot replace the loop with a string function call.

Are you really sure this is needed? So far, I've been able to trigger the
"infinite recursion" bug only if `-ffreestanding` wasn't provided. As soon as I
add `-ffreestanding` (which also implies `-fno-builtin`) I cannot trigger it
anymore: https://godbolt.org/z/WEEGfrz8G

**Comment by skeeto** [comment]
> trying out a "libc-free" platform layer

That's a nice read! Easy to follow, and some new-to-me tricks, like that 
ud2 in _start.

> musl has actually been trying to move away from -Os

Interesting link, thanks! I've noticed -Os preferring the div instruction 
myself, and also thought that, yes, it saves a few bytes but it's clearly 
not worth it. I expect, and want, that sort of thing from the new -Oz. If 
I was worried about it, I'd probably just use -O2 rather than bother with 
a custom set of optimizations. Though for a major project like musl, that 
effort will pay for itself.

> have you considered using `upx`?

I've used it a few times when embedding large, uncompressed assets. With 
upx transparently compressing, I didn't have to deal with it myself. At 
least for images, QOI has come to fill that role. Otherwise it seems kind 
of overkill for what I want.

I'd most want to use it on Windows, a platform where I actually distribute 
binaries. However, "security" tools hate upx, and often block binaries 
using it. Malware authors have trashed the reputation of this cool tool.

> I tried to use `ptrdiff_t` as the size parameter.

I'd prefer ptrdiff_t, too, of course! Though for standard string functions 
I figure I should carefully follow the letter of the law just in case.

> my concern was the "removing volatile from pointer" part

Ah, got it. My thoughts are, as I'm sure you've seen, that "variables 
aren't volatile, operations are volatile" and so on with un/signed, 
atomic, etc. C expresses these properties through the type system rather 
than explicit operators (e.g. how Java and JavaScript have distinct 
signed/unsigned shift operators), which is certainly ergonomic. By that 
thinking, an implementation is forbidden from optimizing out a volatile 
operation regardless of the underlying variable.

> Are you really sure this is needed?

Hmm, you're right! I thought I had tried with -fno-builtin, but apparently 
not. It's the same in older GCC versions, too. I had determined Clang and 
MSVC pay attention to the function name and will not generate a recursive 
call (try changing the name then watch Clang) under normal circumstances, 
so I was only worried about GCC. Looks like I don't need to worry about 
this. Another problem solved by -fno-builtin!

**Comment by N-R-K** [comment]
(Putting this here so I can find it in the future)

clang/llvm seems to have some specific "inline" builtin for `memcpy` and `memset` which guarantees no libc call emission:
https://clang.llvm.org/docs/LanguageExtensions.html#guaranteed-inlined-copy

gcc doesn't seem to support it. Found this thread where someone asked for it and it seems to have been rejected:
https://gcc.gnu.org/pipermail/gcc/2021-January/234717.html

**Comment by skeeto** [comment]
Thanks, @N-R-K, I didn't know about those! That's exactly the sort of thing I've been wanting.
